// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHrrRLZ9UetnUBoxeIxtGK6R59of2-HRk',
    appId: '1:946263966195:web:c1e691a21542f0af21d286',
    messagingSenderId: '946263966195',
    projectId: 'emesse-c9236',
    authDomain: 'emesse-c9236.firebaseapp.com',
    storageBucket: 'emesse-c9236.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB3dLS3ot2y7bJQI_FOxq9yQCYRH_2crk',
    appId: '1:946263966195:android:b5672d9d64a4bae521d286',
    messagingSenderId: '946263966195',
    projectId: 'emesse-c9236',
    storageBucket: 'emesse-c9236.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5rQCRWD8SjQFk5HDZ5WEawSruxFxMIMk',
    appId: '1:946263966195:ios:162a8967525df1af21d286',
    messagingSenderId: '946263966195',
    projectId: 'emesse-c9236',
    storageBucket: 'emesse-c9236.firebasestorage.app',
    androidClientId: '946263966195-6336o48tsustmqu8r8ssden4437o83g7.apps.googleusercontent.com',
    iosBundleId: 'com.kkstechnologies.maparoisse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5rQCRWD8SjQFk5HDZ5WEawSruxFxMIMk',
    appId: '1:946263966195:ios:162a8967525df1af21d286',
    messagingSenderId: '946263966195',
    projectId: 'emesse-c9236',
    storageBucket: 'emesse-c9236.firebasestorage.app',
    androidClientId: '946263966195-6336o48tsustmqu8r8ssden4437o83g7.apps.googleusercontent.com',
    iosBundleId: 'com.kkstechnologies.maparoisse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHrrRLZ9UetnUBoxeIxtGK6R59of2-HRk',
    appId: '1:946263966195:web:f8e3e01cf04d22b021d286',
    messagingSenderId: '946263966195',
    projectId: 'emesse-c9236',
    authDomain: 'emesse-c9236.firebaseapp.com',
    storageBucket: 'emesse-c9236.firebasestorage.app',
  );
}
